---
name: Create DB commands from DBML schema definition

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  create-db-commands:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [ mysql, postgresql ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dbml-cli
        run: npm install -g @dbml/cli

      - name: Generate SQL commands from DBML
        run: |
          dbml2sql --${{ matrix.db }} -o qwparity_schema_${{ matrix.db }}.sql qwparity_schema.dbml

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: qwparity_schema_${{ matrix.db }}.sql
